
drop table if exists sequencing.wnv_pos_2022;
create table if not exists sequencing.wnv_pos_2022
(
    sampleid             text,
    location_id          text,
    entered_date         date,
    species              text,
    species_abbreviation text,
    number_in_pool       int,
    entered_by_tecnician text,
    district             text,
    section              text,
    latitude             double precision,
    longitude            double precision,
    zipcode              int,
    city                 text,
    state                text,
    habitat              text,
    land_use             text,
    surveillance_type    text,
    test_date            text,
    disease              text,
    final_result         text,
    result_binary        text,
    testing_technician   text,
    extracted            text,
    pulledfromplate      text,
    rt                   text,
    targetpcr            text,
    bcu01                text,
    indexpcr             text,
    bcu02                text,
    kapaquant            text,
    tapestation          text,
    sequenced            text,
    sequenceobtained     text,
    sequenceonnextstrain text,
    pims                 text,
    notes                text,
    x                    text
);

drop table if exists sequencing.wnv_coav_2021;
create table if not exists sequencing.wnv_coav_2021
(
    sampleid             text,
    agency_code          text,
    calculated_city      text,
    state                text,
    longitude            double precision,
    latitude             double precision,
    collection_date      date,
    trap_type            text,
    species              text,
    species_abbreviation text,
    sex_condition        text,
    num_count            int,
    test_target          text,
    test_value           text,
    extraction           text,
    extractiontype       text,
    extractionplatename  text,
    reversetranscription text,
    initialpcr           text,
    indexed              text,
    sequenced            text,
    pims                 text
);