drop table if exists sequencing.wnv_pos_2021;
create table if not exists sequencing.wnv_pos_2021
(
    sample_id            text,
    location_id          text,
    entered_date         date,
    epiweek              int,
    species              text,
    species_abbreviation text,
    number_in_pool       int,
    entered_by_tecnician text,
    district             text,
    section              text,
    latitude             double precision,
    longitude            double precision,
    zipcode              text,
    city                 text,
    state                text,
    habitat              text,
    land_use             text,
    surveillance_type    text,
    test_date            date,
    disease              text,
    final_result         text,
    result_binary        int,
    testing_technician   text,
    extracted            text,
    pulled_from_plate    text,
    rt                   text,
    tpcr                 text,
    bcu_01               text,
    index_pcr            text,
    bcu_02               text,
    kapa_quant           text,
    fa                   text,
    sequenced            text,
    sequenceobtained     text,
    sequenceonnextstrain text,
    pims                 text,
    notes                text
);

