---
type: "Config file for read pipeline"

sequence_directory: "/home/cridenour/tmp/test_data/TGN-MiSeq1265"
adapter_file: "config/combined_adapter_primers.fasta"
reference_genome: "config/WNVLineage1"
output_directory: "OutputDirectory"
