reference_genome: "/scratch/cridenour/Projects/VECTR/WNVHeppNextstrain/wnv_nextstrain/sample_processing/config/WNVLineage1"
sequence_directory: "/TGenNextGen/TGN-NextSeq1k_0003/"
output_directory: "NextSeq1k_0003_new_snakemake"
adapter_file: "/scratch/cridenour/Projects/VECTR/WNVHeppNextstrain/wnv_nextstrain/sample_processing/config/combined_adapter_primers.fasta"

